profile_page_home:
    path:     /
    defaults: { _controller: EPFProjetsProfileBundle:Profile:index }

profile_view:
    path:      /{id}
    defaults: { _controller: EPFProjetsProfileBundle:Profile:view }
    requirements:
        id: \d+

profile_add:
    path:      /add
    defaults: { _controller: EPFProjetsProfileBundle:Profile:add }

profile_edit:
    path:      /edit
    defaults: { _controller: EPFProjetsProfileBundle:Profile:edit }
    
me_profile:
    path:      /me
    defaults: { _controller: EPFProjetsProfileBundle:Profile:me }
