<?php

namespace EPFProjets\ProfileBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{

  public function getPageAcc(){
    $qb = $this->createQueryBuilder('a');

    $qb -> orderBy('a.nbreVues', 'DESC')
        -> setMaxResults( 10 );

    return $qb
    ->getQuery()
    ->getResult()
  ;
  }

}
