<?php

namespace EPFProjets\ProfileBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{

  public function getPageAcc(){
    $qb = $this->createQueryBuilder('a');

    $qb -> orderBy('a.nbreVues', 'DESC')
        -> setMaxResults( 10 );

    return $qb
    ->getQuery()
    ->getResult()
  ;
  }

  public function getRecherche($data){
    $qb = $this->createQueryBuilder('a');
    $qb ->innerJoin('a.user', 'c')
        ->addSelect('c')
        ;
    if($data['sexe'] != '*'){
    $qb -> where('c.sexe = :usexe')
          -> setParameter('usexe', $data['sexe']);
    }
    if($data['region'] != '*'){
    $qb -> where('a.region = :aregion')
        -> setParameter('aregion', $data['region']);

    }
    if($data['name'] != ''){
      $qb -> where('c.name = :uname')
          -> setParameter('uname', $data['name']);
    }
    if($data['surname'] != ''){
      $qb -> where('c.surname = :usurname')
          -> setParameter('usurname', $data['surname']);
    }
    $qb -> orderBy('a.nbreVues', 'DESC');

    return $qb
    ->getQuery()
    ->getResult()
  ;
  }


}
