<?php

namespace EPFProjets\NotificationBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
  public function getNbrOfUnread($userId){
    $qb = $this -> createQueryBuilder('a')
                -> where('a.idUser = :uid')
                -> setParameter('uid', $userId)
                -> andwhere('a.seen = false');

    return count($qb->getQuery()->getResult());

  }

  public function seenNotif($userId){
    $qb = $this -> createQueryBuilder('a')
                -> where('a.idUser = :uid')
                -> setParameter('uid', $userId)
                -> andwhere('a.seen = false');
    $em = $this->getEntityManager();

    foreach ($qb->getQuery()->getResult() as $notif) {
      $notif->setSeen(true);
      $em->persist($notif);
      var_dump($notif);
    }
    $em->flush();
  }

}
